#%RAML 1.0 DataType
type: object
properties:
  Name:
    displayName: "Location Code"
    description: "Location Code JAXT1"
    type: string
    required: false
  Location:
    displayName: "Location Type"
    description: "Event Source Location Type Terminal "
    type: string
    required: false
 